### ISSUE TITLE
create a display version of the frontend

### ISSUE THREAD

**Issue by edcous** [codeths/ethsbell-rewrite#109]
Per Mr. Chan's request, we should create a version of the frontend that can be deployed on TVs that does not have the navbar.

**Comment by mswider** [comment]
This exists already.
[https://ethsbell.app/?fullscreen=true](https://ethsbell.app/?fullscreen=true)

**Comment by edcous** [comment]
Ah, I figured it might, thanks.On Jan 10, 2024, at 2:54 PM, mswider ***@***.***> wrote:﻿
This exists already.
https://ethsbell.app/?fullscreen=true
