### ISSUE TITLE
Update to stable rust

### ISSUE THREAD

**Issue by asportnoy** [codeths/ethsbell-rewrite#86]
Requires updating rocket to [v5.0 (currently RC)](https://github.com/SergioBenitez/Rocket/milestone/8). It's basically ready to go but has not had any updates recently. Supposedly it is [not abandoned](https://github.com/SergioBenitez/Rocket/discussions/1957). We might want to just update to the RC.

The build caching from the v2.0.0 is ineffective on nightly rust since it has to rebuild each time.

- [ ] Update Rocket & make any required changes (and any other dependencies)
- [ ] Update Dockerfile
- [ ] Update README

**Comment by spaghetus** [comment]
Rocket 0.4.10 no longer compiles on nightly rust (#98) which is concerning

**Comment by spaghetus** [comment]
Will be fixed in #107
